PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT
  ?label
  ?score
  (GROUP_CONCAT(DISTINCT ?alias; SEPARATOR=";;;") AS ?synonyms)
  ?id
  (GROUP_CONCAT(DISTINCT ?info; SEPARATOR=";;;") AS ?infos)
WHERE {
  { ?id rdf:type owl:Class }
  UNION { ?id rdf:type owl:DatatypeProperty }
  UNION { ?id rdf:type up:Taxon }
  UNION { ?id rdf:type up:Database }
  UNION { ?id rdf:type up:Concept }
  UNION { ?id rdf:type up:Enzyme }
  UNION { ?id rdf:type up:Proteome }
  UNION { ?id rdf:type up:Chromosome }
  OPTIONAL { ?id rdfs:label ?label }
  OPTIONAL {
    { ?id up:scientificName ?alias }
    UNION { ?id up:otherName ?alias }
    UNION { ?id up:commonName ?alias }
    UNION { ?id up:mnemonic ?alias }
    UNION { ?id up:synonym ?alias }
    UNION { ?id <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> ?alias }
    UNION { ?id <http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym> ?alias }
  }
  BIND(0 AS ?score)
  OPTIONAL {
    { ?id rdfs:comment ?info }
    UNION { ?id <http://purl.obolibrary.org/obo/IAO_0000115> ?info }
  }
}
GROUP BY ?label ?score ?id
ORDER BY DESC(?score)
