PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT
  ?label
  ?score
  (GROUP_CONCAT(DISTINCT ?alias; SEPARATOR=";;;") AS ?synonyms)
  ?id
  (GROUP_CONCAT(DISTINCT ?info; SEPARATOR=";;;") AS ?infos)
WHERE {
  {
    SELECT ?p (COUNT(?p) AS ?count)
    WHERE { ?s ?p ?o }
    GROUP BY ?p
  }
  ?id wikibase:claim ?p .
  ?id rdfs:label ?label .
  FILTER(LANG(?label) = "en")
  OPTIONAL { ?id skos:altLabel ?alias FILTER(LANG(?alias) = "en") }
  ?id wikibase:propertyType ?type .
  FILTER(?type != wikibase:ExternalId)
  OPTIONAL {
    { ?id schema:description ?info FILTER(LANG(?info) = "en") }
    UNION
    {
      ?id wdt:P1647/rdfs:label ?sub_label .
      FILTER(LANG(?sub_label) = "en")
      BIND(CONCAT("is subproperty of ", ?sub_label) AS ?info)
    }
  }
}
GROUP BY ?label ?score ?id
ORDER BY DESC(?score)
